apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana/loki-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.78.5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki