apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.9.5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tempo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true